#!/bin/bash

# a repo with files used below
export COMMON_GIT="https://github.com/sumguytho/fedora_common.git"
export COMMON_GIT_DIR="common"
export TMP_DIR="../fedora_deploy_tmp"
export PROFILE_PIC="common/tierm.jpg"
# wallpaper
export WALLP="common/XT39323.jpg"
# lock screen background, also used as sddm background
export LOCKS="common/windowslock.jpg"
export GRUB_THEME_REPO="https://github.com/mateosss/matter"
export GRUB_THEME_REV="2fe52efe52902d8b80384168782b6019ce1e8db3"
# a simple profile that enables the theme
export KONSOLE_PROFILE="my/CustomProfile.profile"
# https://store.kde.org/p/1462616
export KONSOLE_THEME="common/MateriaDark.colorscheme"
# manually edited xml files meant to disable session toolbar
# can be found at https://github.com/KDE/konsole/blob/master/desktop/
export KONSOLE_TOOLBARS_REPO="https://github.com/KDE/konsole"
export KONSOLE_TOOLBARS_REV="3bf1a9586c2440086c82642c43e00ede5f89e560"
export KONSOLE_TOOLBARS_FIX="my/toolbars.patch"
export SIMPLE_COLLATE="simple_collate.py"
# https://store.kde.org/p/1433200/
export SPLASH_THEME_GZ="common/BeautifulTreeAnimation.tar.gz"
# a desktop file template for ghidra sre
export GHIDRA_TEMPL="my/Ghidra.desktop"
# a mimeapps.list config file
export DEFAULT_APPS="my/mimeapps.list"
export ECLIPSE_TEMPL="my/Eclipse.desktop"
export TRASH_DESKTOP="my/trash.desktop"
export FIREFOX_SETTINGS="my/user.js"
export CODIUM_SETTINGS="my/settings.json"
