#!/bin/bash

if [ $# -lt 2 ]; then
	exit -1
fi

PREF_DIR="/opt/google/chrome/extensions"
PREF_FILE="$PREF_DIR/$1.json"
UPD_URL="https://clients2.google.com/service/update2/crx"
sudo mkdir -p "$PREF_DIR"
sudo printf '{\n  "external_update_url": "%s"\n}\n' "$UPD_URL" > "$PREF_FILE"
echo Added \""$PREF_FILE"\" ["$2"]

# https://askubuntu.com/questions/1063331/how-to-install-google-chrome-extensions-though-terminal
