#!/bin/bash
# the rest of the packages
# https://github.com/NationalSecurityAgency/ghidra/releases
export GHIDRA_ZIP="https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.2_build/ghidra_10.2.2_PUBLIC_20221115.zip"
# https://github.com/Windscribe/Desktop-App/releases
export WINDSCRIBE_RPM="https://github.com/Windscribe/Desktop-App/releases/download/v2.4.11/windscribe_2.4.11_x86_64.rpm"
# https://www.umlet.com/download/
export UMLET_ZIP="https://www.umlet.com/download/umlet_15_0/umlet-standalone-15.0.0.zip"
# https://www.rarlab.com/download.htm
export RAR_GZ="https://www.rarlab.com/rar/rarlinux-x64-612.tar.gz"
# https://www.eclipse.org/downloads/packages/release
export ECLIPSE_GZ="https://mirror.dogado.de/eclipse/technology/epp/downloads/release/2022-12/R/eclipse-java-2022-12-R-linux-gtk-x86_64.tar.gz"
